### ISSUE TITLE
vamp plugin packages missing description (F35)

### ISSUE THREAD

**Issue by jn64** [audinux/fedora-spec#11]
vamp packages such as `vamp-bbc-vamp-plugins` and `vamp-cqvamp` are missing descriptions:

```
$ dnf info vamp-bbc-vamp-plugins
Available Packages
Name         : vamp-bbc-vamp-plugins
Version      : 1.1
Release      : 1.fc35
Architecture : x86_64
Size         : 61 k
Source       : bbc-vamp-plugins-1.1-1.fc35.src.rpm
Repository   : copr:copr.fedorainfracloud.org:ycollet:audinux
Summary      : bbc-vamp-plugins VAMP plugin
URL          : https://github.com/bbc/bbc-vamp-plugins
License      : Apache-2.0
Description  : %{description}
```

The src package apparently has description:

```
$ dnf info bbc-vamp-plugins.src
Available Packages
Name         : bbc-vamp-plugins
Version      : 1.1
Release      : 1.fc35
Architecture : src
Size         : 57 k
Source       : None
Repository   : copr:copr.fedorainfracloud.org:ycollet:audinux
Summary      : A BBC collection of audio feature extraction algorithms
URL          : https://github.com/bbc/bbc-vamp-plugins
License      : Apache-2.0
Description  : This is a collection of audio feature extraction algorithms written
             : in the Vamp plugin format by BBC Research and Development.
```

**Comment by jn64** [comment]
> For the descriptions, some vamp plugins are a little short in their descriptions. I will check if I am able to my something more in the corresponding debian packages.

Oh, I wasn't bothered by short descriptions, it's the issue that some packages like `vamp-bbc-vamp-plugins.x86_64` literally have `%{description}` instead of the description text. It seems [this is the relevant part in the spec file?](https://github.com/audinux/fedora-spec/blob/master/vamp-plugins/bbc-vamp-plugins.spec#L28)

But if some packages are lacking descriptions, I can help with writing them.

**Comment by ycollet** [comment]
Thanks for the clarification :)
If you want to participate to the packaging, welcome !

**Comment by ycollet** [comment]
Bad surprise ... Most of the sources of the vamp plugins are unreachable because the main website is down. But luckily, all these source files are packaged in src.rpm. On my way to fix all the problems with vamp plugins.

**Comment by ycollet** [comment]
All the plugins are being rebuilt excepted segmentino. segmentino needs to access the down website. So, I will wait until this website is up and running.

**Comment by ycollet** [comment]
Site web resonding now. I fixed the sgementino packaging to include all the sources inside the tar.gz and removed the call to repoint.

**Comment by ycollet** [comment]
I close the bug. If the problem is still here, please repon it.
