### ISSUE TITLE
Make the JUCE package useful

### ISSUE THREAD

**Issue by jpcima** [audinux/fedora-spec#14]
The JUCE package (current 7.0.1) can be simplified by using the cmake build+install procedure, that exists since JUCE 7.

Not only it's simpler, but it installs a hierarchy that is actually useful to a developer.
One can create a project and type `find_package(JUCE REQUIRED)` in cmake to start right away.
Current package does not provide a cmake find module.

@ycollet

**Comment by ycollet** [comment]
The debian package git repo:
https://salsa.debian.org/multimedia-team/juce/-/tree/master

**Comment by ycollet** [comment]
I updated juce to 7.0.2.
I will build next version (or realease a new version of the package) where I will build everything with cmake and install the required files for cmake.

**Comment by jpcima** [comment]
Nice, thank you. I will try this in a moment.
One remark: the package description is outdated. The newer one has mention of LV2 support, and removed the mention of live-coding which is an abandoned feature.

**Comment by jpcima** [comment]
This creates a weird folder hierarchy
`cp -ra docs/doxygen/doc/ %{buildroot}/%{_datadir}/JUCE-%{version}/doc/`

It gives: `/usr/share/JUCE-7.0.2/doc/doc/`

**Comment by jpcima** [comment]
>Can you check if it works for you ?

Woking fine, when tried with a small example program.
[juce_hello.tar.gz](https://github.com/audinux/fedora-spec/files/9363055/juce_hello.tar.gz)

**Comment by ycollet** [comment]
Thanks a lot.
I will fix the doc generation and probably put this doc into another package.

**Comment by jpcima** [comment]
You may want to consider this patch as well.
It fixes the Juce's native font system that selects Italic by default.
It's a bug which I reported upstream just now.
You might have seen this italics problem happen before, and the "juce_hello" above also is affected.
(example https://user-images.githubusercontent.com/1494920/183043746-0844b5dd-a3b5-4d3d-b1cb-6bdf780db60c.png)

[JUCE-7.0.2-linux-font-default.patch.gz](https://github.com/audinux/fedora-spec/files/9364119/JUCE-7.0.2-linux-font-default.patch.gz)

**Comment by ycollet** [comment]
Thanks for the patch. I will add it
