### ISSUE TITLE
yabridge support libraries not found

### ISSUE THREAD

**Issue by jpcima** [audinux/fedora-spec#15]
The support libraries are installed in `lib64`, but the program looks for them inside `lib`.

On `yabridgectl sync`, there is a problem.
```
Error: Could not find 'libyabridge-chainloader-vst2.so' in either '/usr/lib' or '/home/jpc/.local/share/yabridge/'. You can override the default search path using 'yabridgectl set --path=<path>'.
```

This problem has a workaround, however
`yabridgectl set --path=/usr/lib64/vst`

It fails on carla's attempt to update the plugin list.
```
Could not find 'libyabridge-vst2.so'
```

**Comment by jpcima** [comment]
@ycollet
it's because all these files must go to libdir, not libdir/vst

https://github.com/audinux/fedora-spec/blob/4f028dcbe70bd87dbef0503e745cf48f6833a2d2/yabridge/yabridge.spec#L66-L70

**Comment by ycollet** [comment]
Thanks for the report. I fix that ASAP.

**Comment by ycollet** [comment]
Spec fixed and package rebuilt. Can you check on your side that it works now ?

**Comment by jpcima** [comment]
It does work, thanks. 64-bit plugins only
do you consider to build with the bit bridge for 32-bits plugins?
cf. https://github.com/robbert-vdh/yabridge#32-bit-bitbridge

**Comment by ycollet** [comment]
Thanks for the link. I will ass that part soon.

**Comment by ycollet** [comment]
A new build will be available in some minutes. 
Can you try this one ?

**Comment by jpcima** [comment]
It works fine. Thank you.
