### ISSUE TITLE
Geonkick for Fedora 35?

### ISSUE THREAD

**Issue by Crono23** [audinux/fedora-spec#2]
Can you provide geonkick package for Fedora 35 COPR repo?

**Comment by ycollet** [comment]
Hmm, I though it was already the case ....
The package is present on Fedora 34 but during the rebuild for Fedora 35, this package was skipped.
I will rebuild this package ASAP.

**Comment by Crono23** [comment]
Thank you!

**Comment by ycollet** [comment]
Normally, it's fixed. Geonkick 2.8.0 is now available on Fedora 35. Tell me if it's OK for you.

**Comment by Crono23** [comment]
Tried it just now and it works. Thanks!
