### ISSUE TITLE
Surge-XT VST3 crashes any host in which it's opened

### ISSUE THREAD

**Issue by jpcima** [audinux/fedora-spec#21]
It crashes as soon as it trying to create the instance.

An assertion raises, which possibly is benign under normal conditions, but I thought release binaries are supposed to be built with assertions turned off (?). (with the flag `-DNDEBUG`, that is)

```
/usr/include/c++/12/array:208: constexpr std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) [with _Tp = int; long unsigned int _Nm = 16; reference = int&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
zsh: IOT instruction (core dumped)  carla
```

**Comment by ycollet** [comment]
I will check with upstream if such a problem has been reported. I will also check if some of the flags added by the fedora problem can trigger or not the problem.
