### ISSUE TITLE
JJazzLab

### ISSUE THREAD

**Issue by andycampbell-uk** [audinux/fedora-spec#23]
Hello! Do you think you could include JJazzLab in your amazing repo?

[JJazzLab](https://www.jjazzlab.com/en/)

This looks like a really fun replacement for the deprecated LinuxBand

Thank you (and especially thank you for making audio on Fedora amazing)

**Comment by ycollet** [comment]
Thanks for the ticket.
I checked. It looks like the installation is possible.
I was able to build, and load and example. Need to do some patches for installation.
I will keep you informed.

**Comment by andycampbell-uk** [comment]
That's fantastic, thank you!

**Comment by ycollet** [comment]
There is a first version of the package in the repo.
Can you try it ?

**Comment by andycampbell-uk** [comment]
Wow, that was fast!  Thank you

The package installed with no issues.

I see this error when starting from the command line - I did not test if this also happens with the original package, but I will do that soon.
===
exec /bin/bash /usr/share/jjazzlab/platform/lib/nbexec --jdkhome  --clusters /usr/share/jjazzlab/jjazzlabx --userdir /home/andy/.jjazzlabx/dev --cachedir /home/andy/.cache/jjazzlabx/dev  --branding jjazzlabx 
/usr/bin/which: no javac in (/usr/lib64/qt-3.3/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/andy/bin)
Oct 17, 2022 5:22:56 PM org.netbeans.ProxyURLStreamHandlerFactory register
SEVERE: No way to find original stream handler for jar protocol
java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.net.URLStreamHandler java.net.URL.handler accessible: module java.base does not "opens java.net" to unnamed module @31b5d23
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at org.netbeans.ProxyURLStreamHandlerFactory.register(ProxyURLStreamHandlerFactory.java:59)
	at org.netbeans.JarClassLoader.<clinit>(JarClassLoader.java:117)
	at org.netbeans.MainImpl.execute(MainImpl.java:153)
	at org.netbeans.MainImpl.main(MainImpl.java:60)
	at org.netbeans.Main.main(Main.java:58)
===
This does not prevent the app from running, and the app starts and seems to work great!

Minor issues
:: Missing an icon, plus the app shows with name "java-lang-Thread" when using alt-tab
:: The Sample songs fail due to missing Rhythm files - I need to do a bit more research on that.  I will update the ticket when I have found what is requried
:: The app optionally depend on FluidSynth or QSynth plus a specific SoundFont - it's not a big issue to download it, but it might be nice addition to package that SoundFont also (https://musical-artifacts.com/artifacts/1036)

Thanks

**Comment by ycollet** [comment]
I think this is a java "warning" about deprecated method and about a library not found.
On my side JJazzlab was working. I was able to play and example.

**Comment by andycampbell-uk** [comment]
I notice that this might be more complicated than I thought...
On the github page for [JJazzLab-X](https://github.com/jjazzboss/JJazzLab-X) , I it says "To see the JJazzLab-X capabilities download and try the JJazzLab application at [www.jjazzlab.com](https://www.jjazzlab.com/), it's a JJazzLab-X distribution which bundles the YamJJazz music generation engine based on Yamaha style files."

So, there are two programs - jjazzlabx (which is in your package) and jjazzlab which is distributed as a binary.  

If I download the binary version of JJazzLab (jazzlab) from the product website, it starts with a JJazzLab splash screen, and it can import rhythm files etc.  This can play all the sample songs.
When I start JJazzLab-X (jazzlabx) from the rpm it starts with an NetBeans splash screen, plus gives the stream error and it can not import rhythm files.  This can plan songs, but cannot import the sample songs correctly since it cannot find the rhythm files

**Comment by ycollet** [comment]
OK, thanks for the tests. I will try to fix that ASAP :)

**Comment by andycampbell-uk** [comment]
I think the problem might be that jjazzlab might contain a component which is not opensource (I am still investigating)

**Comment by ycollet** [comment]
Yes, it's possible.
I am a little bit stuck of fedora 37. But I will try to find a solution on my side.

**Comment by ycollet** [comment]
For Jazz, you can also try Impro-Visor ...
https://sourceforge.net/projects/impro-visor/
There is a package is this repo too.

**Comment by andycampbell-uk** [comment]
Thank you!  I will check that out as well - I had not seen that before.

**Comment by ManzoroB** [comment]
I have some issues to report to. The "jjazlab.desktop" file have an error: Exec=jjazlab, it should be "jjazlabx". And i have the problem on import rythms as well. Sometimes there is problems with delays on sound. Tricky, now is ok. (I have to do some configurations on my system maybe?). 
Cool software for educational purposes. Thanks!!

**Comment by ycollet** [comment]
I repackaged the binary version. Fixed

**Comment by andycampbell-uk** [comment]
Everything is looking good for me.  I'm doing a bit more testing, but so far everything is working as expected.  Thanks
