### ISSUE TITLE
Remove emacs/w3m-el requires from supercollider?

### ISSUE THREAD

**Issue by jn64** [audinux/fedora-spec#34]
https://github.com/audinux/fedora-spec/blob/07dbad68a76c46e6310848449c0a54c1b48ca615/supercollider/supercollider.spec#L10

`supercollider` main package doesn't need either of these. Even for `supercollider-emacs` subpackage, the user might have emacs installed from source. So there shouldn't be requires.

Although, if wanted, there can be `Suggests: emacs w3m-el` for `supercollider-emacs`. But then it should be consistent for the other subpackages (vim and gedit).

What do you think?

**Comment by ycollet** [comment]
I have never used emacs with supercollider. I used scide.
I will check your suggestion and if it's OK (in other packages like debian or arch), I will do as you recommend.

**Comment by jn64** [comment]
Hm so, [Fedora spec](https://src.fedoraproject.org/rpms/supercollider/blob/rawhide/f/supercollider.spec) also requires emacs (and qjackctl for some reason). I guess it's carried over from CCRMA.

[openSUSE spec](https://build.opensuse.org/package/view_file/multimedia:apps/supercollider/supercollider.spec?expand=1) doesn't have extra requires.

I downloaded latest rpm `supercollider-3.13.0-5.fc38.x86_64` from Audinux and force install without emacs. scide/sclang/scsynth seem to work fine.

**Comment by ycollet** [comment]
Thanks for the analysis. I will patch the spec tonight.

**Comment by ycollet** [comment]
I am currently updating the spec ...

**Comment by ycollet** [comment]
Fixed
