### ISSUE TITLE
lv2-padthv1 (subpackage) updated without padthv1 (main package)

### ISSUE THREAD

**Issue by jn64** [audinux/fedora-spec#36]
Previous build: `lv2-padthv1` and `padthv1` both 0.9.30-2

[new build](https://copr.fedorainfracloud.org/coprs/ycollet/audinux/build/6003831/): `lv2-padthv1` 0.9.31-2 built, without `padthv1`. Can't upgrade `lv2-padthv1` because it has strict version requires:

https://github.com/audinux/fedora-spec/blob/c6829c100c300aa51164e999fc1454825efdf6d6/padthv1/padthv1.spec#L46-L49

The [spec file in the build](https://download.copr.fedorainfracloud.org/results/ycollet/audinux/fedora-38-x86_64/06003831-padthv1/padthv1.spec) is different from [this repo](https://github.com/audinux/fedora-spec/blob/master/padthv1/padthv1.spec), it's missing the whole `%files` section for the main package.

**Comment by ycollet** [comment]
Yes I was surprised that the standalone application was missing during the build.
I need to check the cmake options, but I think there is a bug in padthv1 ...
If I am not able to rebuild the standalone application, I will open a ticket.

**Comment by jn64** [comment]
Oh I see. Thanks

**Comment by ycollet** [comment]
````
-- Checking for module 'jack>=0.100.0'
--   Found jack, version 1.9.17
CMake Warning at CMakeLists.txt:210 (message):
  *** JACK library not found.
```

Problem with jack detection. I installed pipewire-jack-devel. Maybe the problem comes from here.

**Comment by jn64** [comment]
I don't see `pipewire-jack-audio-connection-kit-devel` in the new spec, only commented out `#BuildRequires: jack-audio-connection-kit-devel`

**Comment by ycollet** [comment]
It's not in the spec, it's installed locally and you can't have both pipewire-jack-audio-connection-kit-devel and jack-audio-connection-kit-devel installed locally. And If I install jack-audio-connection-kit-devel I must uninstall pipewire-jack-audio-connection-kit too. A little mess :)

**Comment by jn64** [comment]
Hm, you can build using mock locally? I'm not sure how it relates to Copr builds.

Or maybe padthv1 can be built with pipewire-jack-audio-connection-kit-devel?

**Comment by ycollet** [comment]
Yes, right now I am using mock. But the  build via mock is a little bit longer than without mock :)

**Comment by ycollet** [comment]
OK it's fixed now. I will open a ticket for pipewire-jack-audio-connection-kit-devel detection.

**Comment by ycollet** [comment]
I will update again the package. Desktop file not correctly installed.

**Comment by jn64** [comment]
Ah ok, thanks

**Comment by ycollet** [comment]
Fixed
