### ISSUE TITLE
spectacle name conflict with KDE spectacle screenshot tool in Fedora repos

### ISSUE THREAD

**Issue by jn64** [audinux/fedora-spec#39]
Audinux `spectacle` package (spectrum analyzer) conflicts in name with Fedora `spectacle` package (KDE screenshot tool)

I think our package must be renamed.

## Problem

- Since Audinux package has a lower version, it cannot be installed by `dnf install spectacle`.
- ~~Even if you specify version/repo to get the Audinux package, dnf is confused by the metadata of both packages, and will install Fedora package's dependencies (qt/kde packages).~~

**Comment by ycollet** [comment]
Thanks a lot for this check !

**Comment by jn64** [comment]
[Upstream already chose the name `spectacle-analyzer` because of this conflict](https://github.com/jpcima/spectacle/issues/7#issuecomment-615517728). We should rename the package to that.

(I'm not sure of the process, if you need to take care of anything in the scripts or website)

**Comment by jn64** [comment]
Yes, we can't use `Obsolete:` here.

**Comment by ycollet** [comment]
Yes, but we must be really careful not to obsolete the spectacle KDE package :)
That's why I think it's better not to use obsolete and just add a message on the website.

**Comment by jn64** [comment]
It seems like dnf was not confused, but I am...

Somehow, the Audinux package on Copr is actually the KDE spectacle. Look at the spec file or build log of the last build: https://copr.fedorainfracloud.org/coprs/ycollet/audinux/build/5678346/

**Comment by ycollet** [comment]
Hmm; excellent. I really don't know what happened here ???
I will remove ASAP all builds of spectable in the repo. I will wait for the renaming of the spec are rebuild spectacla after that.

**Comment by ycollet** [comment]
Just checked and removed all the builds of spectacle.
