### ISSUE TITLE
orca name and file conflicts with Fedora repo

### ISSUE THREAD

**Issue by jn64** [audinux/fedora-spec#40]
1. Audinux `orca` package (esoteric programming language) conflicts in name with Fedora `orca` package (screen reader).

   Same problem as `spectacle`, users cannot install our package easily. I suggest renaming to `orca-lang`

2. The packages also have file conflicts `/usr/bin/orca` and `/usr/share/orca/`. Not sure how to resolve. Blunt solution would be to simply add `Conflicts: orca` to prevent installation of both packages. (The number of users who want to install both `orca` screen reader and `orca` lang is probably 0)

**Comment by ycollet** [comment]
Go for orca-lang. And maybe, if we rename /usr/share/orca into /usr/share/orca-lang this should be enough.
I will also put a warning for this package renaming on the website.

**Comment by jn64** [comment]
Oh, you're right. `/usr/share/orca` is just example files and docs and can be renamed.

Looks like the binary can also be renamed safely. So if we rename to `/usr/bin/orca-lang`, there is no need to add `Conflicts: orca`.

**Comment by jn64** [comment]
Should I rename the spec file too, or just change the `Name:`?

**Comment by ycollet** [comment]
Just change the name, it'll be easier I think.
