### ISSUE TITLE
Qtractor does not start

### ISSUE THREAD

**Issue by henning** [audinux/fedora-spec#51]
I'm trying to run qtractor(-mao) to check its clap plugin support. 

But it's not starting. Via GUI just nothing happens, when I run it in the console, I get:

```
$ qtractor 
Gtk-Message: 21:17:29.375: Failed to load module "pk-gtk-module"

(qtractor:159321): GLib-GObject-CRITICAL **: 21:17:29.383: cannot register existing type 'GtkWidget'

(qtractor:159321): GLib-GObject-CRITICAL **: 21:17:29.383: cannot add class private field to invalid type '<invalid>'

(qtractor:159321): GLib-GObject-CRITICAL **: 21:17:29.383: cannot add private field to invalid (non-instantiatable) type '<invalid>'

(qtractor:159321): GLib-GObject-CRITICAL **: 21:17:29.383: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(qtractor:159321): GLib-GObject-CRITICAL **: 21:17:29.383: cannot register existing type 'GtkBuildable'

(qtractor:159321): GLib-GObject-CRITICAL **: 21:17:29.383: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed

(qtractor:159321): GLib-CRITICAL **: 21:17:29.383: g_once_init_leave: assertion 'result != 0' failed

(qtractor:159321): GLib-GObject-CRITICAL **: 21:17:29.383: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(qtractor:159321): Gtk-CRITICAL **: 21:17:29.383: gtk_widget_get_style_context: assertion 'GTK_IS_WIDGET (widget)' failed

(qtractor:159321): Gtk-CRITICAL **: 21:17:29.383: gtk_style_context_lookup_color: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(qtractor:159321): Gtk-CRITICAL **: 21:17:29.383: gtk_style_context_get_background_color: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed

(qtractor:159321): GLib-GObject-CRITICAL **: 21:17:29.383: cannot register existing type 'GtkWidget'

(qtractor:159321): GLib-GObject-CRITICAL **: 21:17:29.383: cannot add class private field to invalid type '<invalid>'

(qtractor:159321): GLib-GObject-CRITICAL **: 21:17:29.383: cannot add private field to invalid (non-instantiatable) type '<invalid>'

(qtractor:159321): GLib-GObject-CRITICAL **: 21:17:29.383: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
```

Looks like some gtk library problem, but I dont understand what to do about it.

(Not very important to myself, as I already found out on Ubuntu that qtractor seems not to have clap support, despite the clap website says so, but maybe it's helpful to know that the application doesn't run.)

**Comment by ycollet** [comment]
Did you try qtractor from fedora or qtractor-mao from audinux repository ?

**Comment by ycollet** [comment]
On my side qtractor is starting. But I use qtractor-mao package.
I know there is a problem with pipewire-jack and qtractor from fedora. That's why I created this qtractor-mao package.
qtractor from fedora freeze at startup.

**Comment by henning** [comment]
i checked again to be sure and it was really qtractor-mao... but I think I also tried the other one the day before yesterday and it has a similar or same problem.

Maybe a dependency problem that you dont see because you already have a necessary dependency installed before?

**Comment by ycollet** [comment]
Can you try this command ?
```
dnf list installed | grep qtractor
```

**Comment by henning** [comment]
yes:

$ dnf list installed | grep qtractor
^[[3~qtractor-mao.x86_64                                  0.9.38-1.fc39                       @copr:copr.fedorainfracloud.org:ycollet:audinux

**Comment by ycollet** [comment]
I will try tomorrow on Fedora 39. I am on Fedora 38 ...

**Comment by henning** [comment]
In case the display system is relevant, i am on wayland, didn't test with X11.

**Comment by ycollet** [comment]
I am on Wayland too.
You can try:
```
GDK_BACKEND=x11 qtractor
```

**Comment by ycollet** [comment]
Last time, the bug was due to a problem which shows up with pipewire-1.0.0.
On Fedora 38, I am still at pipewire-1.0.0 but fedora 39 is at pipewire-1.0.1 ...

**Comment by ycollet** [comment]
Found this ticket on qtractor repo: https://github.com/rncbc/qtractor/issues/431

**Comment by ycollet** [comment]
Try:
```
pw-jack qtractor
```

**Comment by henning** [comment]
interesting that I didnt find this ticket when googling... 

but the command changes nothing.

**Comment by jn64** [comment]
I can repro with qtractor-mao on F38 Xfce, except I don't have the first line of the output. `pk-gtk-module` is from the package `PackageKit-gtk3-module` but I think is unrelated to the actual problem preventing launch. I don't have PackageKit at all.

For the actual problem, I found the clue here: https://bbs.archlinux.org/viewtopic.php?id=214147&p=2#p1637233

> The reason why Qt5 programs segfault with QGtkStyle in XFCE and other desktop environments is that GTK+ plarform theme (which gets font and icons settings from GTK+ and creates GTK+ file dialogs) which loads in these DEs now builds with gtk3, which is incompatible with QGtkStyle.

qtractor uses Qt6, but it seems the problem is similar.

## Solution

Install `qgnomeplatform-qt6`

### Alternative solution

Install `qt6ct` and set `QT_QPA_PLATFORMTHEME`:

```
QT_QPA_PLATFORMTHEME=qt6ct qtractor
```

Note you only need either one, not both.

---

About fixing the package, I'm not sure if `qgnomeplatform-qt6` is installed/necessary on KDE. @ycollet are you using KDE, and do you have this installed?

**Comment by ycollet** [comment]
Yes,  I am using KDE and no qgnomeplatform-qt6 is not installed. @henning are you using KDE ?

**Comment by jn64** [comment]
Maybe we can do some conditional requires like qbittorrent package https://src.fedoraproject.org/rpms/qbittorrent/blob/66ec58df7e17b426436ac962c0d08342d61165aa/f/qbittorrent.spec#_55

But instead of listing every GTK DE, we can exclude KDE:

```
Requires: (qgnomeplatform-qt6%{?_isa} unless plasma-desktop)
```

I didn't test yet.

Reference: https://rpm-software-management.github.io/rpm/manual/boolean_dependencies.html

**Comment by ycollet** [comment]
Thanks for this link. Looks got to me. I will add this tomorrow..

**Comment by jn64** [comment]
> (Not very important to myself, as I already found out on Ubuntu that qtractor seems not to have clap support, despite the clap website says so, but maybe it's helpful to know that the application doesn't run.)

Qtractor certainly supports CLAP, since 0.9.27 https://github.com/rncbc/qtractor/blob/46969e733b42cd7bddaecd81c200a7ca11329164/ChangeLog#L261

Seems you need to be on Ubuntu 23.04 or later https://packages.ubuntu.com/search?keywords=qtractor

**Comment by ycollet** [comment]
Just tested the current qtractor. I added SurgeXT / Clap version on a MIDI track and it worked.

**Comment by henning** [comment]
> Yes, I am using KDE and no qgnomeplatform-qt6 is not installed. @henning are you using KDE ?

No, I use gnome.

Having installed  qgnomeplatform-qt6 doesn't change anything - neither with qtractor-mao nor the original fedora qtractor.

The other hint from  @jn64 works, but only with qtractor-mao
Which is what we want to fix here in first place, but it's an interesting difference... I notice the -mao package also has two additional dependencies.

**Comment by jn64** [comment]
> Having installed qgnomeplatform-qt6 doesn't change anything - neither with qtractor-mao nor the original fedora qtractor.

Seems like qtractor on F38/39 is built with Qt5. Can you try qgnomeplatform-qt5?

Not sure why it doesn't work for qtractor-mao though. Any change in the console output?On 2024-01-22T12:15:56.000+08:00, Henning Sprang  wrote:

**Comment by ycollet** [comment]
The Fedora qtractor has a bug with pipewire which makes it freeze. So, installing qgnomeplatform-qt5 will not make qtractor working on F38 / F39 because of this pipewire bug :)

**Comment by ycollet** [comment]
@henning what works for you ? It is:
```
QT_QPA_PLATFORMTHEME=qt6ct qtractor
```
If this the case, I found that it's possible to add an environment variable in the desktop file. So, I will fix the problem by adjusting qtractor desktop file ...

**Comment by henning** [comment]
@ycollet sorry for replying so slow, a bit busy with other things...

yes that was the one that worked for me, with the audinux qtractor.

let me know if i should test something!

slightly OT but you might be interested to hear:
by the way, the main reason i wanted to try qtractor and clap was to test a bug in Cardinal clap from the official release which cannot be used because it doesn't find resources and therefore modules. 
I found out that the problem doesn't exist in the audinux version.

**Comment by ycollet** [comment]
OK, I will try to do a build this week-end.

For cardinal, the main difference I see: on Fedora, we are using system dependencies and not the embedded ones ...
