### ISSUE TITLE
puredata complains  - installing tk package manually helps

### ISSUE THREAD

**Issue by henning** [audinux/fedora-spec#54]
after installing puredata and trying to run it, the result is:

```
$ pd
sh: line 1: wish: command not found
```

it keeps running but I dont see if it's doing anything.
As I'm new to pd i looked a bit around, and found out that there is also pd-gui, but that too doesn't run:

```
$ pd-gui
/usr/lib64/puredata/tcl/pd-gui.tcl: line 3: exec: wish: not found
```

That one exits immediately then.

After finding what this is about and manually installing the tk package, i get a running pd gui - with both commands pd and pd-gui.

I think this dependency should be installed automatically, at least with puredata-gui (which anyway is automatically installed when I install puredata).

**Comment by ycollet** [comment]
Ah ! Thanks a lot.
Last time I checked this package was a long time ago.
Nowadays I only used puredata via hvcc (a puredata to binary compiler).
Thanks for the PR !

**Comment by henning** [comment]
just trying to help where i come along and find these things ;)

I also needed it for hvcc in a way - I wanted to build a synth or at least an oscillator to build with http://builder.mod.audio/ and deploy on my MOD Dwarf... first tried plugdata - nice but a bit too unstable still. SO I wanted to use the original and discovered these things. Unfortunately it still didn't build in cloud builder, which uses hvcc. Something wrong with the select i used... hvcc seems to require an argument always, while pd doesn't. 
For a first few hours with PD it was fine.

I assume it's fixed as it's merged - but I can try to find the time to actually test it when the updated package is there (not on my FC39 Laptop now) tomorrow.

**Comment by ycollet** [comment]
For the use of hvcc to build a plugin, I used a Makefile I've got from vswell plugin:
https://github.com/audinux/fedora-spec/blob/master/vswell/vswell.spec

I used this customized makefile to build wstd plugins:
https://github.com/audinux/fedora-spec/blob/master/wstd/wstd-3q.spec

**Comment by henning** [comment]
thanks for the hint! ;)

i tested the changes made to the package already weeks ago but forgot to close this ticket.
