### ISSUE TITLE
Bespoke Synth not available on Fedora 36

### ISSUE THREAD

**Issue by carnage-mode** [audinux/fedora-spec#6]
Can you provide it or are there some hurdles I'm unaware of?

**Comment by ycollet** [comment]
Yes, yes, not yet.

**Comment by ycollet** [comment]
I had a problem during the rebuild of JUCE. I fixed one problem some hours ago and I will try to fix the remaining one in BespokeSynth. The switch to gcc 12 was a little bit hard :)

**Comment by carnage-mode** [comment]
Thanks :heart:

**Comment by ycollet** [comment]
Build fixed !
A header was missing ...
It's now available on Fedora 36.

**Comment by carnage-mode** [comment]
Will it take long to be available for install?

**Comment by ycollet** [comment]
normally no, but try:
$ dnf --refresh install BespokeSynth

**Comment by carnage-mode** [comment]
Works perfectly :smile: Thanks a lot for the timely replies and fixes :)
