### ISSUE TITLE
vst-sparta fails to install

### ISSUE THREAD

**Issue by ntonnaett** [audinux/fedora-spec#60]
vst-sparta depends on unavailable libsaf.so.1.3.2.

```
➜  sudo dnf install vst-sparta         
Last metadata expiration check: 2:05:14 ago on Mon 09 Sep 2024 09:39:08 AM PDT.
Error: 
 Problem: conflicting requests
  - nothing provides libsaf.so.1.3.2()(64bit) needed by vst-sparta-1.7.1-1.fc40.x86_64 from copr:copr.fedorainfracloud.org:ycollet:audinux
(try to add '--skip-broken' to skip uninstallable packages)
```

**Comment by ycollet** [comment]
Thanks for the report ... I am checking this ASAP.

**Comment by ycollet** [comment]
The problem will be solved in 1 or 2 hours ...

**Comment by ntonnaett** [comment]
This was quick. Thank you!

**Comment by ycollet** [comment]
I hope this is fixed. I activated the build of VST3 / LV2 versions of the plugin and fixed a rpath problem with the plugins.
Can you test the plugin and tell me if it's OK for you ?

**Comment by ntonnaett** [comment]
That's great! I was wondering about the VST3 and LV2 versions. Installation works now. I'll test if the plugins run.

**Comment by ntonnaett** [comment]
Some plugins are missing:
- ambiBIN
- ambiDEC
- binauralizer
- binauralizerNF
- dirass
- 6DoFconv
- PowerMap
- SLDoA
- Spreader
- TrackerTest

**Comment by ycollet** [comment]
I will check for the missing plugins.

**Comment by ycollet** [comment]
For some of the missing plugins, I found how to activate some and these ones will not be available on Linux:
```
if(NOT UNIX OR APPLE)
    add_subdirectory(_SPARTA_dirass_)
    add_subdirectory(_SPARTA_powermap_)
    add_subdirectory(_SPARTA_sldoa_)
else()
```
And for trackertest, there is a directory in the SPARTA achive, but nothing in the cmake files is building this part of the code. Maybe a plugin to come ...

**Comment by ycollet** [comment]
Update finished. You can try the missing plugins now.
