### ISSUE TITLE
VST plugins cannot be found by my daw

### ISSUE THREAD

**Issue by carnage-mode** [audinux/fedora-spec#62]
I installed a couple plugins in a toolbx container alongside Bespoke. LV2 plugins work fine but VST ones are not found even though they have been installed

**Comment by ycollet** [comment]
Thanks for the report. I will check. Maybe a patch will be required to change a "/usr/lib/vst" to "/usr/lib64/vst".
I will check that bespokesynth only supports VST2 plugins and not VST3.

**Comment by carnage-mode** [comment]
> Thanks for the report. I will check. Maybe a patch will be required to change a "/usr/lib/vst" to "/usr/lib64/vst".
> I will check that bespokesynth only supports VST2 plugins and not VST3.

I checked with reaper and the plugins are not being detected there either. Also, Bespoke seems to support both VST3 and LV2 as of late.

I'm on Fedora 41

**Comment by ycollet** [comment]
OK. I will check tomorrow on my side and will keep you informed

**Comment by ycollet** [comment]
Want plugin have you installed ?

**Comment by carnage-mode** [comment]
Surge xt and odin2

**Comment by ycollet** [comment]
I checked and BespokeSynth seems to only work with VST2 plugins and not with VST3.
Still checking (I am fixing a requirements problem with ffmpeg / ffmpeg-free).

**Comment by ycollet** [comment]
You mean surge and odin are not installed in /usr/lib64/vst3 directory ?

**Comment by carnage-mode** [comment]
Yes 
![image](https://github.com/user-attachments/assets/efe458ac-540f-4d91-89d7-924bfb71236b)

**Comment by ycollet** [comment]
How did you install odin2 ?
```
$ dnf install odin2
or
$ dnf install vst3-odin2
```
Sorry for this question but I am really surprised this directtory is empty ... :)

**Comment by carnage-mode** [comment]
Tried the vst3-odin2 package and now the directory shows up, but bespoke still has trouble scanning it

**Comment by carnage-mode** [comment]
Had no idea that the package would be named `vst3-odin2`. Do you packages all vst3s as `vst3-*` ?

**Comment by ycollet** [comment]
Some times ago, installing odin2 installed the command line version + vst3 / clap / lv2 / vst2.
But with surge, the package was huge and I decided to split the plugins package by version:
- odin2 for command line version
- vst3-odin2 for vst3
- license-odin2 for some readme / license files.
I think this is how things are made on other distro.
And it's quite practical. If you want to list all the vst3 packages:
```
$ dnf search "vst3-*"
```
