### ISSUE TITLE
Last update broke yabridge

### ISSUE THREAD

**Issue by Skyr** [audinux/fedora-spec#63]
Since the update to yabridge 5.1.1 (and after running yabridgectl sync), all plugins report "could not find 'yabridge_plugin_init' in 'libyabridge-...'". I tried using yabridge in conjunction with the Fedora 40 wine package and winehq-staging with no success.

**Comment by ycollet** [comment]
Thanks for the report ... I will try to dig into the github repo of yabridge. 
In the mean time, you can try to force install the preceding version ?

**Comment by ycollet** [comment]
Ah ... Yes. I had some problems with yabridge while building for f40. What was the last working version for you ?

**Comment by Skyr** [comment]
I assume it was 5.1.0 since I regularly pull updates.
Aaaand: Sorry for the rushed formulation of the issue... "broke it for me" might be more fitting, since the whole wine-yabridge-music stuff has quite a lot of moving parts... I totally appreciate the time and energy you invest in maintaining this repo, and it's an invaluable resource when making music on Fedora!

**Comment by ycollet** [comment]
Thanks for this comment. I am on it. Trying to find a solution ...

**Comment by ycollet** [comment]
Can you post a "list" of command you made which leads to this problem ?
I checked the package and libraries seems OK.
Just saw that a COPR from the yabridge dev is available:
https://copr.fedorainfracloud.org/coprs/patrickl/yabridge/

**Comment by Skyr** [comment]
It happens the moment the vst host tries to load the plugin. Happens both in Bitwig and in Carla.

**Comment by ycollet** [comment]
OK. Thanks. I foud a patch for a problem with yabridgectl from the yabridge dev. Testing ...

**Comment by ycollet** [comment]
```
[Info]: Scanning: /home/ycollette/.vst/yabridge/Synth2.so
terminate called without an active exception
Error: signal 6
 ---8<---
  /lib64/libc.so.6(+0x40d00) [0x7effd584fd00]
  /lib64/libc.so.6(+0x99664) [0x7effd58a8664]
  gsignal
  abort
  /lib64/libstdc++.so.6(+0xa5da9) [0x7effd5aa5da9]
  /lib64/libstdc++.so.6(+0xb7c4c) [0x7effd5ab7c4c]
  std::unexpected()
  /lib64/libyabridge-vst2.so(+0x7ad4a) [0x7effd4645d4a]
  /lib64/libstdc++.so.6(+0xe7564) [0x7effd5ae7564]
  /lib64/libc.so.6(+0x976d7) [0x7effd58a66d7]
  /lib64/libc.so.6(+0x11b60c) [0x7effd592a60c]
 --->8---
Scan Failed.

```

**Comment by ycollet** [comment]
Downloaded surge VST3 for Windows 64 bits and yabridge worked.
So, maybe the problem is related to 32 bits plugins. I've got one which failed so I am able to test.

**Comment by Skyr** [comment]
I tried to follow your lead with the 32 bit stuff... and remembered that yabridgectl has the ability to set paths to the binaries manually. Trying to set them resulted in Rust error messages (looked like serialization issue), so I assumed that perhaps the config file has changed in some way? I deleted it, ran a sync, re-added my paths, ran the sync again.
Now Bitwig recognized all 64 bit plugins :tada:  I have a few 32 bit binaries, they reported a missing yabridge-host-32.exe. So there might be missing something in the rpm? But - for me, personally - the important (64 bit) stuff works again.

Thanks for your fast response and error-digging! Sorry I can't pinpoint the cause (and the fix) better.

**Comment by ycollet** [comment]
I fixed the serialization problem. The patch I found on the COPR of the author of yabridge was for that. I don't know why this patch has not been merged to the yabridge repo ...
I also found (I hope) the bug with vst 32 bits. wine 32 bits needs to be installed too ... 
A new package has been built with all these changes.

**Comment by Skyr** [comment]
Dumped the packages from WineHQ, installed stock Wine from Fedora 40, upgraded - works perfectly! :tada: 
Thanks for your help and your quick response!
