### ISSUE TITLE
Faust does not provide devel headers

### ISSUE THREAD

**Issue by jcelerier** [audinux/fedora-spec#65]
Hello,
while trying to get a build of [ossia score](https://github.com/ossia/score) working with as many distro packages as I can, I see that the faust packaged in Audinux does not install the development headers.

For instance 

    #include <faust/dsp/poly-llvm-dsp.h>

etc etc.
Should there be a faust-devel package maybe ?

**Comment by ycollet** [comment]
Yes  ... you're right. I don't remember where I got this spec but I noticed that.
The headers are in the faust-osclib package. I put the update of the faust spec in my todo list.
I will try to fix it this week.

**Comment by ycollet** [comment]
faust-osclib-devel ... not faust-osclib

**Comment by ycollet** [comment]
I updated the package.

**Comment by jcelerier** [comment]
great, it works with faust-devel here now :)
